### ISSUE TITLE
Cannot find task "add". 

### ISSUE THREAD

**Issue by jkarmel** [smerritt/facebook_test_users#1]
I was really excited to see this because managing test users can be a real pain. However I don't seem to be having much luck with it. After I installed it the only cammand that seemed to work was help. Why I ran

fbtu add --app-id=[app_id] --app-secret=[app_secret] --name=jeremy_dev

I got the error

Could not find task "add".

**Comment by aspiers** [comment]
I see this too.  It's something to do with subcommands - I believe the correct invocation is supposed to be

```
fbtu apps add --app-id=...
```

but somewhere between thor 0.14.6 and current, it broke.  So the idea is that `apps` subcommands manage the fb app registry, and then the `users` subcommands perform test user actions using a selected fb app from that registry.

**Comment by aspiers** [comment]
OK, this is actually the fault of `cli.rb` for not using Thor in the right way.  Prior to wycats/thor@8a2e4cc8 and wycats/thor@68c51272 (about 15 commits after the [`v0.16.0` release tag](https://github.com/wycats/thor/tree/v0.16.0)), it accidentally worked, but doesn't any longer.  I have a patch to fix this which I'll submit shortly.

**Comment by smerritt** [comment]
Looks like this got fixed by the referenced commit.
